### PR TITLE
Ban acres unmute forever

### PR DESCRIPTION
**Pull request by DerZade**
Yeetus deletus.

### CODE REVIEW

**Comment by Fusselwurm** [comment]
I need context here – both because I cant find documentation on it, and also because other groups - [notably TTT](https://wiki.tacticalteam.de/de/Technik/CBASettings) - have this setting *en*abled.

From looking at the ACRE sources, setting this to false… disables the automatic unmuting of other clients on connecting to a TS server? something like this?

**Comment by nomisum** [comment]
Yes, you cant mute yourself in TS anymore while connected to the server with default (true).

I am not aware of side effects - maybe you might forget to unmute? Any more risks?

**Comment by DerZade** [comment]
> I am not aware of side effects - maybe you might forget to unmute? Any more risks?

As far as my understanding goes this is the exact use-case. Making sure that players are not muted by accident. 
With TFAR we never had such issues, therefore I do not see the need to enable this setting ever.

**Review by Fusselwurm — APPROVED** [review]

**Comment by OverlordZorn** [comment]
grafik

**Comment by DerZade** [comment]
> grafik

@PulsarNeutronStar Thank you very much for the research. I guess then this PR is obsolete and I'll never join a ACRE mission again. 😅

**Comment by OverlordZorn** [comment]
> > grafik
> 
> @PulsarNeutronStar Thank you very much for the research. I guess then this PR is obsolete and I'll never join a ACRE mission again. 😅

just get gud ;)

**Comment by OverlordZorn** [comment]
grafik

**Pull request closed without merging**
